### ISSUE TITLE
Please explain 'tz_ical'

### ISSUE THREAD

**Issue by superjunky** [thobaier/Synology-API-PhpStorm-HTTP-Client#1]
Hi,

Your code is the only one I have found that showed how to create events trough the Synology api.
It appears that without the 'tz_ical' parameter, the api trows an internal error.

Wil you please explain what it does, why it is required, and most of all where/how did you find this piece of info?
It would help me out a lot. Thanks!

Kind regards,
Robbie

**Comment by thobaier** [comment]
Hi Robbie,

its a long time ago but i remember that the "tz_ical" is the TIMEZOME of the I-Clandar entry. I slightly remember that i need to set the timezone in my calls. Anyway since the Synology UI is totally ajax based you can see any calls with their payloads in the browser developer tools when clicking and triggring actions in the Synology UI. So you have a perfect place to catch all calls in any Synology application. Most of them are ajax based.

**Comment by superjunky** [comment]
Thats perfect advice. Thanks a bunch for taking the time to reply.
